### ISSUE TITLE
Update prework parts that map to current Laboratoria/bootcamp

### ISSUE THREAD

**Issue by lupomontero** [Laboratoria/admission-curriculum#11]
In order to start bringing this content up to date with `Laboratoria/bootcamp`, here is a list of the different _pre-work_ parts and how they map to current content in `Laboratoria/bootcamp`:

- [x] [01-welcome-and-orientation](https://github.com/Laboratoria/admission-curriculum/tree/master/admission-es/03-prework/01-welcome-and-orientation) -> ?
- [ ] [02-growth-mindset](https://github.com/Laboratoria/admission-curriculum/tree/master/admission-es/03-prework/02-growth-mindset) -> ?
- [ ] [03-why-learn-to-code](https://github.com/Laboratoria/admission-curriculum/tree/master/admission-es/03-prework/03-why-learn-to-code) -> ?
- [x] [04-your-first-website](https://github.com/Laboratoria/admission-curriculum/tree/master/admission-es/03-prework/04-your-first-website) -> [html/01-intro/01-your-first-website](https://github.com/Laboratoria/bootcamp/tree/master/topics/html/01-intro/01-your-first-website)
- [ ] [05-quiz](https://github.com/Laboratoria/admission-curriculum/tree/master/admission-es/03-prework/05-quiz) -> ?
- [x] [06-values-data-types-and-operators](https://github.com/Laboratoria/admission-curriculum/tree/master/admission-es/03-prework/06-values-data-types-and-operators) -> [javascript/01-basics/01-values-variables-and-types](https://github.com/Laboratoria/bootcamp/tree/master/topics/javascript/01-basics/01-values-variables-and-types)
- [x] [07-variables](https://github.com/Laboratoria/admission-curriculum/tree/master/admission-es/03-prework/07-variables) -> [javascript/01-basics/02-variables](https://github.com/Laboratoria/bootcamp/tree/master/topics/javascript/01-basics/02-variables)
- [ ] [08-self-learning-MDN](https://github.com/Laboratoria/admission-curriculum/tree/master/admission-es/03-prework/08-self-learning-MDN) -> ?
- [x] [09-comments](https://github.com/Laboratoria/admission-curriculum/tree/master/admission-es/03-prework/09-comments) -> [javascript/01-basics/03-comments](https://github.com/Laboratoria/bootcamp/tree/master/topics/javascript/01-basics/03-comments)
- [x] [10-guided-exercises](https://github.com/Laboratoria/admission-curriculum/tree/master/admission-es/03-prework/10-guided-exercises) -> [javascript/01-basics/04-guided-exercises](https://github.com/Laboratoria/bootcamp/tree/master/topics/javascript/01-basics/04-guided-exercises)
- [x] [11-quiz](https://github.com/Laboratoria/admission-curriculum/tree/master/admission-es/03-prework/11-quiz) -> [javascript/01-basics/05-quiz](https://github.com/Laboratoria/bootcamp/tree/master/topics/javascript/01-basics/05-quiz)
- [x] [12-exercises](https://github.com/Laboratoria/admission-curriculum/tree/master/admission-es/03-prework/12-exercises) -> [javascript/01-basics/06-exercises](https://github.com/Laboratoria/bootcamp/tree/master/topics/javascript/01-basics/06-exercises)
- [ ] [13-development-team](https://github.com/Laboratoria/admission-curriculum/tree/master/admission-es/03-prework/13-development-team) -> ?
- [ ] [14-ux-design](https://github.com/Laboratoria/admission-curriculum/tree/master/admission-es/03-prework/14-ux-design) -> [00-intro-ux/00-que-es-uxd/00-que-es-uxd](https://github.com/Laboratoria/curricula-ux/tree/master/00-topics/00-intro-ux/00-que-es-uxd/00-que-es-uxd)
- [ ] [15-ux-design-vs-ui-design](https://github.com/Laboratoria/admission-curriculum/tree/master/admission-es/03-prework/15-ux-design-vs-ui-design) -> ?
- [ ] [16-quiz](https://github.com/Laboratoria/admission-curriculum/tree/master/admission-es/03-prework/16-quiz) -> ?

This issue is a _placeholder_ for tracking progress with this short-term review/update process.

**Comment by raulingg** [comment]
@lupomontero I think we can address the rest of parts to another issue, in this way we can close this issue as the first step to update the prework.  

What do you think ? :thinking:

**Comment by lupomontero** [comment]
> I think we can address the rest of parts to another issue, in this way we can close this issue as the first step to update the prework.

Sounds Good to me...
